print("area".isalpha())
print("Area 51".isalpha())
print("51".isnumeric())
print("Area 51".isnumeric())
print("Area51".isalnum())
print("Area 51".isalnum())
print(" ".isspace())
print(" ".isspace())
print(" k ".isspace())
print(" 4 ".isspace())
print(" ! ".isspace())